contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
default: styles/computer_fairies_old.scss
mastodon: styles/application.scss
mastodon_light: styles/mastodon_light.scss
contrast: styles/contrast.scss